const PLAY = {
  SET_COMPLETE_SEQUENCE: 'SET_COMPLETE_SEQUENCE',
  SET_PARTIAL_SEQUENCE: 'SET_PARTIAL_SEQUENCE',
  SET_PLAYER_SEQUENCE: 'SET_PLAYER_SEQUENCE',
  UDPATE_COMPUTER_TURN_COUNT: 'UDPATE_COMPUTER_TURN_COUNT',
  UPDATE_PLAYER_TURN_COUNT: 'UPDATE_PLAYER_TURN_COUNT',
  SWITCH_TURNS: 'SWITCH_TURNS',
  PLAYER_TURN: 'PLAYER_TURN',
  COMPUTER_TURN: 'COMPUTER_TURN',
  PLAYER_WINS: 'PLAYER_WINS',
  PLAYER_LOSES: 'PLAYER_LOSES',
  PLAYER_CONTINUES: 'PLAYER_CONTINUES'
}

export default PLAY
